### ISSUE TITLE
data['']

### ISSUE THREAD

**Issue by muzhongjiang** [coffeehu/CBoard-v#2]
keys.forEach(key => {
              let itemValue = data[''][value.name][value.aggType][key.join('-')];
              item.value.push(itemValue);
            });

请问 RadarContent.vue 这里的data[''] 是什么意思？

**Comment by coffeehu** [comment]
1、【图表设计】中可看到主要有三个值：Row、Column、Value

2、Row 对应 keys 字段； Column 对应 groups 字段；Value 对应 value 字段。
keys、groups 都是维度，value 为对应的值。

3、因此可以生成一个配置对象如：
`{
  keys: [...],
  groups: [
    ["Canada"], ["Mexico"], ["USA"]
  ],
  value: [...]
}`

4、根据这个配置对象, 结合返回的图标数据，可生成最终的数据对象，格式为：
`{data: {
  Canada: {...},
  Mexico: {...},
  USA: {...}
}}`
可见 data 的字段即为 groups 的成员产生。

5、因此对于 Radar 图，是一个 key-value 的维度，它的 groups 字段为 []。
因此经过处理，数据对象为：
`
{ data: {
  "": {...}
} }
`
即用了一个 "" 来作为字段。
