### ISSUE TITLE
部署访问静态文件404

### ISSUE THREAD

**Issue by uzro** [coffeehu/CBoard-v#4]
你好 
在构建完成，放在服务器目录启动后，提示有静态文件无法访问

截图如下：
![image](https://user-images.githubusercontent.com/20982165/71651708-b4180100-2d5a-11ea-9930-7e42ec6408ab.png)

期待回复
感谢！

**Comment by MF-ZHOU** [comment]
> 你好
> 在构建完成，放在服务器目录启动后，提示有静态文件无法访问
> 
> 截图如下：
> ![image](https://user-images.githubusercontent.com/20982165/71651708-b4180100-2d5a-11ea-9930-7e42ec6408ab.png)
> 
> 期待回复
> 感谢！

你好，你构建成功了吗

**Comment by MF-ZHOU** [comment]
构建成功了，主要改了两个地方
![1](https://user-images.githubusercontent.com/34392842/72684690-c5645a00-3b1d-11ea-8494-05f4fb91fd44.jpg)
![2](https://user-images.githubusercontent.com/34392842/72684691-c5fcf080-3b1d-11ea-84a4-d55890420aa1.jpg)

![image](https://user-images.githubusercontent.com/34392842/72684696-d6ad6680-3b1d-11ea-8e9e-2e587f622e52.png)

**Comment by coffeehu** [comment]
> 构建成功了，主要改了两个地方
> ![1](https://user-images.githubusercontent.com/34392842/72684690-c5645a00-3b1d-11ea-8494-05f4fb91fd44.jpg)
> ![2](https://user-images.githubusercontent.com/34392842/72684691-c5fcf080-3b1d-11ea-84a4-d55890420aa1.jpg)
> 
> ![image](https://user-images.githubusercontent.com/34392842/72684696-d6ad6680-3b1d-11ea-8e9e-2e587f622e52.png)

谢谢，最近一直没有时间上来看
